packages:
  - .
  - playground

catalog:
  '@biomejs/biome': ^2.3.10
  '@changesets/cli': ^2.29.8
  '@types/node': ^25.0.3
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': 5.1.2
  react: ^19.2.3
  react-dom: ^19.2.3
  simple-git-hooks: ^2.13.1
  typescript: ^5.9.3
  vite: ^7.2.7
  vitest: ^4.0.16
  waku: https://pkg.pr.new/wakujs/waku@4edb1b3
  zile: 0.0.13

overrides:
  vite: 'catalog:'
