packages:
  - create-vocs
  - og
  - playgrounds/*
  - site
  - src

strictDepBuilds: true
blockExoticSubdeps: true
minimumReleaseAge: 1440
trustPolicy: no-downgrade

catalog:
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  react: ^19.2.5
  react-dom: ^19.2.5
  typescript: ^5.9.3
