catalog: 
  '@biomejs/biome': ^2.3.10
  '@changesets/cli': ^2.29.8
  '@react-router/dev': ^7.11.0
  '@types/react': '^19.2.7'
  '@types/node': '^25.0.3'
  simple-git-hooks: '^2.13.1'
  react: '^19.2.3'
  typescript: '^5.9.3'
  vite: '^7.2.7'
  vitest: '^4.0.16'
  zile: '0.0.13'

overrides: 
  vite: 'catalog:'

packages:
  - '.'
  - 'playground'