import { theme } from 'zyzz/default'
import { global } from 'zyzz/web'

global({
  '@layer vocs_components': {
    '[data-v-content] > :is(p, h3, h4, h5, h6, hgroup, strong, a, blockquote, ol, ul) + :is(p, h3, h4, h5, h6, hgroup, strong, a, blockquote, ol, ul)':
      { marginTop: 'calc(0.25rem * -2) !important' },
    '[data-v-content] > h2[data-v] + h3[data-v]': { marginTop: 'calc(0.25rem * -2) !important' },
    'h1[data-v]': {
      scrollMarginTop: '6rem',
      fontSize: theme.vars.fontSize['4xl'],
      lineHeight: '1em',
      fontWeight: theme.vars.fontWeight['medium'],
      letterSpacing: '-0.04em',
      color: theme.vars.color.foreground,
    },
    'h2[data-v], section[data-footnotes] h2': {
      scrollMarginTop: 'calc(0.25rem * -5)',
      fontSize: theme.vars.fontSize['2xl'],
      lineHeight: '1em',
      fontWeight: theme.vars.fontWeight['medium'],
      letterSpacing: '-0.025em',
      color: theme.vars.color.foreground,
    },
    'h3[data-v]': {
      scrollMarginTop: 'calc(0.25rem * -4)',
      fontSize: theme.vars.fontSize['xl'],
      lineHeight: '1em',
      fontWeight: theme.vars.fontWeight['medium'],
      letterSpacing: '-0.025em',
      color: theme.vars.color.foreground,
    },
    'h4[data-v]': {
      scrollMarginTop: 'calc(0.25rem * -4)',
      fontSize: theme.vars.fontSize['lg'],
      fontWeight: theme.vars.fontWeight['semibold'],
      letterSpacing: '-0.025em',
      color: theme.vars.color.foreground,
    },
    'h5[data-v]': {
      scrollMarginTop: 'calc(0.25rem * -4)',
      fontSize: theme.vars.fontSize['base'],
      fontWeight: theme.vars.fontWeight['semibold'],
      letterSpacing: '-0.025em',
      color: theme.vars.color.foreground,
    },
    'h6[data-v]': {
      scrollMarginTop: 'calc(0.25rem * -4)',
      fontSize: theme.vars.fontSize['base'],
      fontWeight: theme.vars.fontWeight['semibold'],
      letterSpacing: '-0.025em',
      color: theme.vars.color.foreground,
    },
    '.heading-anchor': {
      marginLeft: theme.vars.spacing[2],
      display: 'inline-flex',
      alignItems: 'center',
      textDecorationLine: 'none',
      opacity: '0%',
      transitionProperty: 'opacity',
      transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
      transitionDuration: '100ms',
    },
    '.heading-anchor-icon': { translate: ' 0.05em', color: theme.vars.color.gray['900'] },
    ':is(h1, h2, h3, h4, h5, h6)[data-v]:hover .heading-anchor, .heading-anchor:focus-visible': {
      opacity: '100%',
    },
    '.heading-anchor:hover .heading-anchor-icon': { color: theme.vars.color.blue['900'] },
    '.heading-anchor[data-copied="true"] .heading-anchor-icon': {
      color: theme.vars.color.green['900'],
    },
    'strong[data-v]': { fontWeight: theme.vars.fontWeight['semibold'] },
    'p[data-v]': { lineHeight: '1.625em', letterSpacing: '0em' },
    'img[data-v]': { height: 'auto', maxWidth: '100%' },
    'hgroup[data-v]': { fontSize: theme.vars.fontSize['4xl'] },
    'hgroup[data-v], :is(article[data-v-content], [data-v-openapi-intro], [data-v-openapi-guide]) > h1[data-v]':
      {
        borderBottomStyle: 'solid',
        borderBottomWidth: '1px',
        borderColor: theme.vars.color.gray['400'],
        paddingBottom: '0.75em',
      },
    'hgroup[data-v] p': {
      marginTop: '0.25em',
      fontSize: theme.vars.fontSize['lg'],
      lineHeight: '1.5em',
      fontWeight: theme.vars.fontWeight['medium'],
      color: theme.vars.color.gray['900'],
    },
    'hgroup[data-v]:not(:last-child), :is(article[data-v-content], [data-v-openapi-intro], [data-v-openapi-guide]) > h1[data-v]:not(:last-child)':
      { marginBlockEnd: 'calc(calc(0.25rem * 8) * calc(1 - )) !important' },
    ':is(article[data-v-content], [data-v-openapi-intro], [data-v-openapi-guide]) > :not(:is(hgroup[data-v], h1[data-v])) + h2:not(:only-child)':
      {
        marginTop: 'calc(0.25rem * 10) !important',
        borderTopStyle: 'solid',
        borderTopWidth: '1px',
        borderColor: theme.vars.color.gray['400'],
        paddingTop: theme.vars.spacing[8],
      },
    ':is(article[data-v-content], [data-v-openapi-intro], [data-v-openapi-guide]) > h3:not(:only-child)':
      { paddingTop: theme.vars.spacing[4] },
    ':is(article[data-v-content], [data-v-openapi-intro], [data-v-openapi-guide]) > h4:not(:only-child), :is(article[data-v-content], [data-v-openapi-intro], [data-v-openapi-guide]) > h5:not(:only-child), :is(article[data-v-content], [data-v-openapi-intro], [data-v-openapi-guide]) > h6:not(:only-child)':
      { paddingTop: theme.vars.spacing[4] },
    'a[data-v], [data-v-link]': {
      display: 'inline-block',
      fontWeight: theme.vars.fontWeight['medium'],
      color: theme.vars.color.foreground,
      textDecorationLine: 'underline',
      textDecorationThickness: '1px',
      textUnderlineOffset: '2px',
      transitionProperty:
        'color, background-color, border-color, outline-color, text-decoration-color, fill, stroke',
      transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
      transitionDuration: '100ms',
      '&:hover': {
        color: theme.vars.color.foreground,
        '@supports (color: color-mix(in lab, red, red))': {
          color: `color-mix(in oklab, ${theme.vars.color.foreground} 80%, transparent)`,
        },
        textDecorationStyle: 'dotted',
      },
    },
    '[data-v-context="info"] a[data-v]': { textDecorationColor: theme.vars.color.blue['900'] },
    '[data-v-context="warning"] a[data-v]': { textDecorationColor: theme.vars.color.amber['900'] },
    '[data-v-context="danger"] a[data-v]': { textDecorationColor: theme.vars.color.red['900'] },
    '[data-v-context="tip"] a[data-v]': { textDecorationColor: theme.vars.color.purple['900'] },
    '[data-v-context="success"] a[data-v]': { textDecorationColor: theme.vars.color.green['900'] },
    'a[data-v-dead-link]': {
      textDecorationColor: theme.vars.color.red['900'],
      textDecorationStyle: 'wavy',
      '&:hover': { textDecorationStyle: 'wavy' },
    },
    'blockquote[data-v]': {
      borderLeftStyle: 'solid',
      borderLeftWidth: '3px',
      borderColor: theme.vars.color.gray['400'],
      backgroundColor: theme.vars.color.gray['100'],
      paddingInline: theme.vars.spacing[4],
      paddingBlock: theme.vars.spacing[3],
      fontSize: '15px',
      color: theme.vars.color.gray['900'],
    },
    '[data-v-badge]': {
      display: 'inline-flex',
      alignItems: 'center',
      borderRadius: theme.vars.borderRadius['md'],
      paddingInline: theme.vars.spacing[2],
      paddingBlock: 'calc(0.25rem * 0.5)',
      verticalAlign: 'middle',
      fontSize: theme.vars.fontSize['xs'],
      lineHeight: 'calc(1 / 0.75)',
      fontWeight: theme.vars.fontWeight['medium'],
      '&[data-v-context="note"]': {
        backgroundColor: theme.vars.color.gray['100'],
        '@supports (color: color-mix(in lab, red, red))': {
          backgroundColor: theme.vars.color.gray['100'],
        },
        color: theme.vars.color.gray['900'],
      },
      '&[data-v-context="info"]': {
        backgroundColor: theme.vars.color.blue['100'],
        '@supports (color: color-mix(in lab, red, red))': {
          backgroundColor: theme.vars.color.blue['100'],
        },
        color: theme.vars.color.blue['900'],
      },
      '&[data-v-context="tip"]': {
        backgroundColor: theme.vars.color.purple['100'],
        '@supports (color: color-mix(in lab, red, red))': {
          backgroundColor: theme.vars.color.purple['100'],
        },
        color: theme.vars.color.purple['900'],
      },
      '&[data-v-context="warning"]': {
        backgroundColor: theme.vars.color.amber['100'],
        '@supports (color: color-mix(in lab, red, red))': {
          backgroundColor: theme.vars.color.amber['100'],
        },
        color: theme.vars.color.amber['900'],
      },
      '&[data-v-context="danger"]': {
        backgroundColor: theme.vars.color.red['100'],
        color: theme.vars.color.red['900'],
      },
      '&[data-v-context="success"]': {
        backgroundColor: theme.vars.color.green['100'],
        '@supports (color: color-mix(in lab, red, red))': {
          backgroundColor: theme.vars.color.green['100'],
        },
        color: theme.vars.color.green['900'],
      },
    },
    'aside[data-v][data-v-callout]': {
      position: 'relative',
      borderRadius: theme.vars.borderRadius['lg'],
      borderStyle: 'solid',
      borderWidth: '1px',
      padding: theme.vars.spacing[3],
      fontSize: theme.vars.fontSize['sm'],
      '@media (width <= 48rem)': {
        marginRight: 'calc(0.25rem * -4)',
        marginLeft: 'calc(0.25rem * -4)',
        borderRadius: '0',
        borderRightStyle: 'solid',
        borderRightWidth: '0px',
        borderLeftStyle: 'solid',
        borderLeftWidth: '0px',
      },
      '&, & [data-v-content]': {
        ':where(& > :not(:last-child))': {
          marginBlockStart: 'calc(calc(0.25rem * 4) * 0)',
          marginBlockEnd: 'calc(calc(0.25rem * 4) * calc(1 - 0))',
          borderStyle: 'solid',
        },
      },
      '& > [data-v-callout-icon]': {
        position: 'absolute',
        marginTop: '0.3rem',
        height: theme.vars.spacing[4],
        width: theme.vars.spacing[4],
      },
      '&[data-v-content] > :not(:is([data-v-callout-icon], [data-v-code-container]))': {
        paddingInlineStart: theme.vars.spacing[6],
      },
      '& [data-v-code-header]': { height: theme.vars.spacing[8] },
      '& [data-v-code-title]': {
        paddingInline: theme.vars.spacing[3],
        fontSize: theme.vars.fontSize['xs'],
        lineHeight: 'calc(1 / 0.75)',
      },
      '& pre': { paddingBlock: theme.vars.spacing[3] },
      '& pre .line': { paddingInline: theme.vars.spacing[4] },
      '&[data-v-context="note"]': {
        borderColor: theme.vars.color.gray['400'],
        backgroundColor: theme.vars.color.gray['100'],
        '@supports (color: color-mix(in lab, red, red))': {
          backgroundColor: theme.vars.color.gray['100'],
        },
        color: theme.vars.color.gray['900'],
      },
      '&[data-v-context="info"]': {
        borderColor: theme.vars.color.blue['400'],
        backgroundColor: theme.vars.color.blue['100'],
        '@supports (color: color-mix(in lab, red, red))': {
          backgroundColor: theme.vars.color.blue['100'],
        },
        color: theme.vars.color.blue['900'],
      },
      '&[data-v-context="warning"]': {
        borderColor: theme.vars.color.amber['400'],
        backgroundColor: theme.vars.color.amber['100'],
        '@supports (color: color-mix(in lab, red, red))': {
          backgroundColor: theme.vars.color.amber['100'],
        },
        color: theme.vars.color.amber['900'],
      },
      '&[data-v-context="danger"]': {
        borderColor: theme.vars.color.red['400'],
        backgroundColor: theme.vars.color.red['100'],
        color: theme.vars.color.red['900'],
      },
      '&[data-v-context="tip"]': {
        borderColor: theme.vars.color.purple['400'],
        backgroundColor: theme.vars.color.purple['100'],
        '@supports (color: color-mix(in lab, red, red))': {
          backgroundColor: theme.vars.color.purple['100'],
        },
        color: theme.vars.color.purple['900'],
      },
      '&[data-v-context="success"]': {
        borderColor: theme.vars.color.green['400'],
        backgroundColor: theme.vars.color.green['100'],
        '@supports (color: color-mix(in lab, red, red))': {
          backgroundColor: theme.vars.color.green['100'],
        },
        color: theme.vars.color.green['900'],
      },
    },
    '[data-v-banner]': {
      position: 'fixed',
      top: theme.vars.spacing[0],
      right: theme.vars.spacing[0],
      left: theme.vars.spacing[0],
      zIndex: 50,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: theme.vars.spacing[4],
      paddingInline: theme.vars.spacing[4],
      paddingBlock: theme.vars.spacing[2],
      fontSize: theme.vars.fontSize['sm'],
      lineHeight: 1.25,
      fontWeight: theme.vars.fontWeight['medium'],
      '&[data-v-context="note"]': {
        backgroundColor: theme.vars.color.gray['100'],
        '@supports (color: color-mix(in lab, red, red))': {
          backgroundColor: theme.vars.color.gray['100'],
        },
        color: theme.vars.color.gray['900'],
      },
      '&[data-v-context="info"]': {
        backgroundColor: theme.vars.color.blue['100'],
        '@supports (color: color-mix(in lab, red, red))': {
          backgroundColor: theme.vars.color.blue['100'],
        },
        color: theme.vars.color.blue['900'],
      },
      '&[data-v-context="tip"]': {
        backgroundColor: theme.vars.color.purple['100'],
        '@supports (color: color-mix(in lab, red, red))': {
          backgroundColor: theme.vars.color.purple['100'],
        },
        color: theme.vars.color.purple['900'],
      },
      '&[data-v-context="warning"]': {
        backgroundColor: theme.vars.color.amber['100'],
        '@supports (color: color-mix(in lab, red, red))': {
          backgroundColor: theme.vars.color.amber['100'],
        },
        color: theme.vars.color.amber['900'],
      },
      '&[data-v-context="danger"]': {
        backgroundColor: theme.vars.color.red['100'],
        color: theme.vars.color.red['900'],
      },
      '&[data-v-context="success"]': {
        backgroundColor: theme.vars.color.green['100'],
        '@supports (color: color-mix(in lab, red, red))': {
          backgroundColor: theme.vars.color.green['100'],
        },
        color: theme.vars.color.green['900'],
      },
    },
    '[data-v-banner-content]': {
      display: 'flex',
      flexWrap: 'wrap',
      alignItems: 'center',
      columnGap: 'calc(0.25rem * 1.5)',
    },
    '[data-v-banner-arrow]': { height: 'calc(0.25rem * 3.5)', width: 'calc(0.25rem * 3.5)' },
    '[data-v-banner-link]': { textDecorationLine: 'underline', textUnderlineOffset: '2px' },
    '[data-v-banner-dismiss]': {
      position: 'absolute',
      right: theme.vars.spacing[4],
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: theme.vars.borderRadius['sm'],
      padding: theme.vars.spacing[1],
      opacity: '70%',
      transitionProperty: 'opacity',
      transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
      transitionDuration: '150ms',
      '&:hover': { '@media (hover: hover)': { opacity: '100%' } },
      '& svg': { height: theme.vars.spacing[4], width: theme.vars.spacing[4] },
    },
    'ol[data-v]': {
      marginBottom: theme.vars.spacing[4],
      listStyleType: 'decimal',
      paddingInlineStart: theme.vars.spacing[5],
      '& &': { listStyleType: 'lower-alpha' },
      '& & &': { listStyleType: 'lower-roman' },
    },
    'li[data-v]': {
      lineHeight: '1.625em',
      '&:not(:last-child)': { marginBottom: theme.vars.spacing[2] },
    },
    'ul[data-v]': {
      listStyleType: 'disc',
      paddingInlineStart: theme.vars.spacing[6],
      '& &': { listStyleType: 'circle' },
      '&.contains-task-list': { listStyleType: 'none', paddingInlineStart: theme.vars.spacing[1] },
    },
    ':is(ol, ul)[data-v] :is(ol, ul)[data-v]': {
      marginBottom: theme.vars.spacing[0],
      paddingInlineStart: theme.vars.spacing[4],
      paddingTop: theme.vars.spacing[2],
      paddingBottom: theme.vars.spacing[0],
    },
    'table[data-v]': {
      display: 'table',
      width: '100%',
      borderSpacing: 'calc(0.25rem * 0) calc(0.25rem * 0)',
      lineHeight: '1.325em',
      '& td': {
        borderBottomStyle: 'solid',
        borderBottomWidth: '1px',
        borderColor: theme.vars.color.gray['400'],
        paddingBlock: theme.vars.spacing[2],
        fontSize: theme.vars.fontSize['sm'],
        '&:first-child': {
          fontWeight: theme.vars.fontWeight['medium'],
          color: theme.vars.color.foreground,
          borderSpacing: 'calc(0.25rem * 0) calc(0.25rem * 0)',
          borderBottomStyle: 'solid',
        },
      },
      '& :is(th, td)': { paddingInline: theme.vars.spacing[3] },
      '& th': {
        borderBottomStyle: 'solid',
        borderBottomWidth: '1px',
        borderColor: theme.vars.color.gray['400'],
        backgroundColor: theme.vars.color.gray['100'],
        paddingBlock: theme.vars.spacing[2],
        textAlign: 'left',
        fontSize: '0.8125rem',
        fontWeight: theme.vars.fontWeight['medium'],
        whiteSpace: 'nowrap',
        color: theme.vars.color.foreground,
        '@supports (color: color-mix(in lab, red, red))': {
          color: `color-mix(in oklab, ${theme.vars.color.foreground} 80%, transparent)`,
        },
        borderSpacing: 'calc(0.25rem * 0) calc(0.25rem * 0)',
        '&[align="center"]': { textAlign: 'center' },
        '&[align="right"]': { textAlign: 'right' },
      },
    },
    'div[data-v-table-wrapper]': {
      marginInline: 'calc(0.25rem * -3)',
      marginBottom: theme.vars.spacing[6],
      overflowX: 'auto',
      borderRadius: theme.vars.borderRadius['lg'],
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      '@media (width < 48rem)': { borderRadius: '0' },
    },
    'div[data-v-benchmarks]': {
      marginBottom: theme.vars.spacing[6],
      '& div[data-v-table-wrapper]': { marginBottom: theme.vars.spacing[0] },
      '& table[data-v]': {
        '& th[data-v-benchmarks-col]:not([align="left"])': { textAlign: 'center' },
        '& td[data-v-benchmarks-cell]': {
          position: 'relative',
          isolation: 'isolate',
          textAlign: 'center',
          whiteSpace: 'nowrap',
          fontVariantNumeric: '   tabular-nums ',
          '&::before': { content: '""', position: 'absolute', inset: '3px', zIndex: -1 },
        },
        '& td[data-v-benchmarks-cell="baseline"]': {
          color: theme.vars.color.gray['900'],
          '&::before': { border: `1px dashed ${theme.vars.color.gray['400']}` },
        },
        '& td[data-v-benchmarks-cell="neutral"]::before': {
          backgroundColor: theme.vars.color.gray['100'],
        },
        '& td[data-v-benchmarks-cell="faster"]::before': {
          backgroundColor: theme.vars.color.green['900'],
          '@supports (color: color-mix(in lab, red, red))': {
            backgroundColor: `color-mix( in srgb, ${theme.vars.color.green['900']} calc(6% + var(--vocs-benchmarks-intensity) * 42%), ${theme.vars.color.gray['100']} )`,
          },
        },
        '& td[data-v-benchmarks-cell="slower"]::before': {
          backgroundColor: theme.vars.color.red['900'],
          '@supports (color: color-mix(in lab, red, red))': {
            backgroundColor: `color-mix( in srgb, ${theme.vars.color.red['900']} calc(6% + var(--vocs-benchmarks-intensity) * 42%), ${theme.vars.color.gray['100']} )`,
          },
        },
        '& td[data-v-benchmarks-cell="missing"]': {
          color: theme.vars.color.gray['800'],
          '&::before': {
            backgroundImage:
              'repeating-linear-gradient( -45deg, #7d7d7d 0 4px, transparent 4px 8px )',
            '@supports (color: color-mix(in lab, red, red))': {
              backgroundImage:
                'repeating-linear-gradient( -45deg, color-mix(in srgb, #7d7d7d 12%, transparent) 0 4px, transparent 4px 8px )',
            },
          },
        },
      },
      '& footer[data-v-benchmarks-legend]': {
        marginTop: theme.vars.spacing[2],
        display: 'flex',
        alignItems: 'center',
        gap: theme.vars.spacing[2],
        fontSize: theme.vars.fontSize['sm'],
        lineHeight: 'calc(1.25 / 0.875)',
        color: theme.vars.color.gray['800'],
        '& [data-v-benchmarks-legend-scale]': {
          height: theme.vars.spacing[2],
          width: theme.vars.spacing[16],
          background: `linear-gradient( to right, ${theme.vars.color.green['900']}, ${theme.vars.color.gray['100']}, ${theme.vars.color.red['900']} )`,
          '@supports (color: color-mix(in lab, red, red))': {
            background: `linear-gradient( to right, color-mix(in srgb, ${theme.vars.color.green['900']} 48%, ${theme.vars.color.gray['100']}), ${theme.vars.color.gray['100']}, color-mix(in srgb, ${theme.vars.color.red['900']} 48%, ${theme.vars.color.gray['100']}) )`,
          },
        },
        '& [data-v-benchmarks-legend-baseline]': {
          marginInlineStart: theme.vars.spacing[4],
          display: 'flex',
          alignItems: 'center',
          gap: theme.vars.spacing[2],
        },
        '& [data-v-benchmarks-legend-swatch]': {
          display: 'inline-block',
          height: 'calc(0.25rem * 3.5)',
          width: theme.vars.spacing[6],
          borderStyle: 'dashed',
          borderWidth: '1px',
          borderColor: theme.vars.color.gray['400'],
          lineHeight: 'calc(1.25 / 0.875)',
        },
      },
    },
    'sup[data-v] > a': {
      marginInlineStart: 'calc(0.25rem * 0.5)',
      color: `${theme.vars.color.foreground} !important`,
      textUnderlineOffset: '2px',
    },
    'hr[data-v]': { borderColor: theme.vars.color.gray['400'] },
    'a.data-footnote-backref': {
      fontSize: theme.vars.fontSize['sm'],
      lineHeight: 'calc(1.25 / 0.875)',
      fontWeight: theme.vars.fontWeight['medium'],
      color: theme.vars.color.gray['900'],
      textUnderlineOffset: '2px',
      fontVariantEmoji: 'text',
      '&:hover': { color: theme.vars.color.foreground },
    },
    'section[data-footnotes]': {
      ':where(& > :not(:last-child))': {
        marginBlockStart: 'calc(calc(0.25rem * 6) * 0)',
        marginBlockEnd: 'calc(calc(0.25rem * 6) * calc(1 - 0))',
      },
    },
    'section[data-footnotes] ol': {
      ':where(& > :not(:last-child))': {
        marginBlockStart: 'calc(calc(0.25rem * 2) * 0)',
        marginBlockEnd: 'calc(calc(0.25rem * 2) * calc(1 - 0))',
      },
    },
    'details[data-v]': {
      ':where(& > :not(:last-child))': {
        marginBlockStart: 'calc(calc(0.25rem * 4) * 0)',
        marginBlockEnd: 'calc(calc(0.25rem * 4) * calc(1 - 0))',
      },
      '& > summary': {
        marginBottom: theme.vars.spacing[0],
        display: 'flex',
        width: '100%',
        cursor: 'pointer',
        alignItems: 'center',
        lineHeight: '1.5em',
        fontWeight: theme.vars.fontWeight['medium'],
        textDecorationThickness: '1px',
        textUnderlineOffset: '2px',
        listStyle: 'none',
        '&:hover': { '@media (hover: hover)': { textDecorationLine: 'underline' } },
        '& + p': { marginTop: theme.vars.spacing[2] },
        '&::-webkit-details-marker': { display: 'none' },
        '&::before': {
          marginRight: '0.25em',
          display: 'inline-block',
          width: '1em',
          height: '1em',
          backgroundColor: 'currentcolor',
          verticalAlign: 'middle',
          transitionProperty: 'transform, translate, scale, rotate',
          transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
          transitionDuration: '200ms',
          content: "''",
          maskImage:
            "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1em' height='1em' viewBox='0 0 24 24'%3E%3Cpath fill='none' stroke='currentColor' stroke-linecap='round' stroke-linejoin='round' stroke-width='3' d='m9 18l6-6l-6-6'/%3E%3C/svg%3E\")",
          maskSize: 'contain',
          maskRepeat: 'no-repeat',
        },
      },
      '&[open] > summary::before': { rotate: '90deg' },
    },
    'aside[data-v] details': {
      ':where(& > :not(:last-child))': {
        marginBlockStart: 'calc(calc(0.25rem * 2) * 0)',
        marginBlockEnd: 'calc(calc(0.25rem * 2) * calc(1 - 0))',
      },
    },
    ':not(aside[data-v]) > details': { color: theme.vars.color.gray['900'] },
    'pre[data-v]': {
      overflowX: 'auto',
      borderRadius: theme.vars.borderRadius['lg'],
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      backgroundColor: theme.vars.color.background['200'],
      paddingBlock: theme.vars.spacing[5],
      '@media (width <= 48rem)': {
        marginInline: 'calc(0.25rem * -4)',
        borderRadius: '0',
        borderRightStyle: 'solid',
        borderRightWidth: '0px',
        borderLeftStyle: 'solid',
        borderLeftWidth: '0px',
        paddingBlock: theme.vars.spacing[4],
        '&&& .line.diff::after': {
          content: 'none',
          borderStyle: 'solid',
          borderRightStyle: 'solid',
          borderLeftStyle: 'solid',
        },
      },
      '& > code': {
        display: 'grid',
        fontSize: '0.875em',
        '& span': {
          textDecoration: 'var(--shiki-dark-text-decoration, inherit)',
          fontWeight: 'var(--shiki-dark-font-weight, inherit)',
          '@media (prefers-color-scheme: light)': {
            textDecoration: 'var(--shiki-light-text-decoration, inherit)',
            fontWeight: 'var(--shiki-light-font-weight, inherit)',
          },
        },
        '& > :is(.line, .twoslash-tag-line)': {
          borderLeftStyle: 'solid',
          borderLeftWidth: '2px',
          borderLeftColor: 'transparent',
          paddingInline: 'var(--vocs-layout-code-block-px)',
          lineHeight: '1.75em',
          borderStyle: 'solid',
          '&.highlighted': {
            borderLeftStyle: 'solid',
            borderLeftWidth: '2px',
            borderColor: theme.vars.color.gray['400'],
            backgroundColor: theme.vars.color.gray['200'],
          },
          '& .highlighted-word': {
            borderRadius: theme.vars.borderRadius['sm'],
            borderStyle: 'solid',
            borderWidth: '1px',
            borderColor: theme.vars.color.gray['400'],
            backgroundColor: theme.vars.color.gray['200'],
            '@supports (color: color-mix(in lab, red, red))': {
              backgroundColor: `color-mix(in oklab, ${theme.vars.color.gray['200']} 70%, transparent)`,
            },
            paddingInline: 'calc(0.25rem * 1.5)',
            paddingBlock: 'calc(0.25rem * 0.5)',
          },
        },
        '&.line-numbers': {
          counterReset: 'line',
          '& > .line': {
            paddingLeft: theme.vars.spacing[3],
            '&::before': {
              marginRight: theme.vars.spacing[3],
              display: 'inline-block',
              width: theme.vars.spacing[4],
              textAlign: 'right',
              color: theme.vars.color.gray['800'],
              content: 'counter(line)',
            },
            '&:not(.diff.remove + .diff.add)::before': { counterIncrement: 'line' },
            '&.diff::after': { content: 'none', borderStyle: 'solid' },
          },
        },
      },
      '&.has-focused': {
        '& .line:not(.focused)': {
          opacity: '30%',
          transitionProperty: 'opacity',
          transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
          transitionDuration: '200ms',
          borderStyle: 'solid',
        },
        '&:hover .line:not(.focused)': { opacity: '100%' },
      },
      '&.has-diff': {
        position: 'relative',
        '& .line.diff': {
          '&::after': { position: 'absolute', left: '8px' },
          '&.add': {
            borderLeftStyle: 'solid',
            borderLeftWidth: '2px',
            borderColor: theme.vars.color.green['900'],
            '@supports (color: color-mix(in lab, red, red))': {
              backgroundColor: theme.vars.color.green['100'],
            },
            backgroundColor: theme.vars.color.green['100'],
          },
          '&.add::after': {
            color: theme.vars.color.green['900'],
            content: "'+'",
            borderStyle: 'solid',
          },
          '&.remove': {
            borderLeftStyle: 'solid',
            borderLeftWidth: '2px',
            borderColor: theme.vars.color.red['900'],
            '@supports (color: color-mix(in lab, red, red))': {
              borderColor: `color-mix(in oklab, ${theme.vars.color.red['900']} 30%, transparent)`,
            },
            backgroundColor: theme.vars.color.red['100'],
          },
          '&.remove::after': {
            color: theme.vars.color.red['900'],
            content: "'-'",
            borderStyle: 'solid',
          },
          '&.remove > span': {
            opacity: '60%',
            filter: '   grayscale(100%)     ',
            borderStyle: 'solid',
          },
        },
      },
    },
    ':not(.shiki) > code': { paddingInline: 'var(--vocs-layout-code-block-px)' },
    'pre[data-v][data-v-wrapped]': {
      overflowX: 'hidden',
      '& > code > .line': { wordBreak: 'break-all', whiteSpace: 'pre-wrap' },
    },
    '[data-v-code-header]': {
      display: 'flex',
      height: theme.vars.spacing[10],
      alignItems: 'center',
      borderTopLeftRadius: '0.5rem',
      borderTopRightRadius: '0.5rem',
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      backgroundColor: theme.vars.color.surface,
      fontSize: theme.vars.fontSize['sm'],
      lineHeight: 'calc(1.25 / 0.875)',
      '@media (width < 48rem)': { borderRadius: '0' },
    },
    '[data-v-code-title]': {
      paddingInline: theme.vars.spacing[4],
      fontSize: '13px',
      fontWeight: theme.vars.fontWeight['medium'],
      letterSpacing: '-0.025em',
      color: theme.vars.color.gray['900'],
    },
    '[data-v-prompt]': {
      cursor: 'pointer',
      overflow: 'hidden',
      borderRadius: theme.vars.borderRadius['lg'],
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      backgroundColor: theme.vars.color.gray['100'],
      '@supports (color: color-mix(in lab, red, red))': {
        backgroundColor: `color-mix(in oklab, ${theme.vars.color.gray['100']} 70%, transparent)`,
      },
    },
    '@media (width <= 48rem)': {
      '[data-v-content] > [data-v-prompt]': {
        marginInline: 'calc(0.25rem * -4)',
        borderRadius: '0',
        borderRightStyle: 'solid',
        borderRightWidth: '0px',
        borderLeftStyle: 'solid',
        borderLeftWidth: '0px',
      },
      '[data-v-steps] [data-v-code-container]': { marginLeft: 'calc(0.25rem * -8) !important' },
      '[data-v-steps] [data-v-callout]': { marginLeft: 'calc(0.25rem * -12) !important' },
      '[data-v-steps] [data-v-callout] [data-v-code-container]': {
        marginLeft: 'calc(0.25rem * -0) !important',
      },
    },
    '[data-v-prompt-header]': {
      display: 'flex',
      height: theme.vars.spacing[12],
      alignItems: 'center',
      justifyContent: 'space-between',
      borderBottomStyle: 'solid',
      borderBottomWidth: '1px',
      borderColor: 'transparent',
      backgroundColor: 'transparent',
      paddingInline: theme.vars.spacing[2],
      transitionProperty:
        'color, background-color, border-color, outline-color, text-decoration-color, fill, stroke',
      transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
      transitionDuration: '150ms',
    },
    '[data-v-prompt][data-expanded="true"] [data-v-prompt-header]': {
      borderColor: theme.vars.color.gray['400'],
    },
    '[data-v-prompt-header]:hover': { backgroundColor: theme.vars.color.gray['100'] },
    '[data-v-prompt-icon]': {
      width: 'calc(0.25rem * 3.5)',
      height: 'calc(0.25rem * 3.5)',
      flexShrink: 0,
      color: theme.vars.color.blue['900'],
    },
    '[data-v-prompt-copy]': {
      display: 'flex',
      height: '100%',
      minWidth: theme.vars.spacing[0],
      flex: 1,
      cursor: 'pointer',
      alignItems: 'center',
      gap: theme.vars.spacing[2],
      borderRadius: theme.vars.borderRadius['md'],
      backgroundColor: 'transparent',
      paddingInline: theme.vars.spacing[2],
      textAlign: 'left',
      fontSize: '14px',
      fontWeight: theme.vars.fontWeight['medium'],
      letterSpacing: '-0.025em',
      color: theme.vars.color.gray['900'],
      transitionProperty:
        'color, background-color, border-color, outline-color, text-decoration-color, fill, stroke',
      transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
      transitionDuration: '100ms',
      '&:hover': { '@media (hover: hover)': { color: theme.vars.color.foreground } },
      '&[data-state="copied"] [data-v-prompt-icon]': { color: theme.vars.color.green['900'] },
      '&[data-state="error"]': { color: theme.vars.color.red['900'] },
    },
    '[data-v-prompt-actions]': {
      display: 'flex',
      alignItems: 'center',
      gap: 'calc(0.25rem * 0.5)',
    },
    '[data-v-prompt-action]': {
      display: 'flex',
      width: theme.vars.spacing[8],
      height: theme.vars.spacing[8],
      cursor: 'pointer',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: theme.vars.borderRadius['md'],
      backgroundColor: 'transparent',
      color: theme.vars.color.gray['900'],
      transitionProperty:
        'color, background-color, border-color, outline-color, text-decoration-color, fill, stroke',
      transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
      transitionDuration: '100ms',
      '&:hover': { '@media (hover: hover)': { color: theme.vars.color.foreground } },
      '& > svg': { width: theme.vars.spacing[4], height: theme.vars.spacing[4] },
    },
    '[data-v-prompt-tooltip]': {
      borderRadius: theme.vars.borderRadius['md'],
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      backgroundColor: theme.vars.color.surface,
      paddingInline: theme.vars.spacing[2],
      paddingBlock: theme.vars.spacing[1],
      fontSize: '12px',
      color: theme.vars.color.foreground,
      boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
    },
    '[data-v-prompt-body]': {
      position: 'relative',
      margin: theme.vars.spacing[0],
      overflow: 'hidden',
      backgroundColor: theme.vars.color.background['200'],
      paddingInline: 'var(--vocs-layout-code-block-px)',
      paddingBlock: theme.vars.spacing[5],
      fontFamily: theme.vars.fontFamily.sans,
      fontSize: '15px',
      lineHeight: 1.7,
      letterSpacing: '0em',
      overflowWrap: 'anywhere',
      whiteSpace: 'pre-wrap',
      color: theme.vars.color.foreground,
      '@media (width <= 48rem)': {
        paddingInline: theme.vars.spacing[4],
        paddingBlock: theme.vars.spacing[4],
      },
      '&::after': {
        content: '""',
        position: 'absolute',
        inset: '0',
        pointerEvents: 'none',
        transform: 'translateX(-120%)',
        background: `linear-gradient( 105deg, transparent 25%, oklch(from ${theme.vars.color.blue['700']} l c h / 10%) 50%, transparent 75% )`,
      },
      '& > code': { paddingInline: theme.vars.spacing[0], fontFamily: theme.vars.fontFamily.sans },
    },
    '[data-v-prompt]:hover [data-v-prompt-body]::after': {
      animation: 'vocs-prompt-shimmer 900ms ease-out',
    },
    '@media (prefers-reduced-motion: reduce)': {
      '[data-v-prompt]:hover [data-v-prompt-body]::after': { animation: 'none' },
    },
    '[data-v-prompt-token="url"]': {
      cursor: 'pointer',
      color: theme.vars.color.blue['900'],
      textDecorationLine: 'underline',
      textDecorationColor: theme.vars.color.blue['700'],
      '@supports (color: color-mix(in lab, red, red))': {
        textDecorationColor: `color-mix(in oklab, ${theme.vars.color.blue['700']} 40%, transparent)`,
      },
      textUnderlineOffset: '2px',
      transitionProperty:
        'color, background-color, border-color, outline-color, text-decoration-color, fill, stroke',
      transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
      transitionDuration: '100ms',
      '&:hover': {
        color: theme.vars.color.blue['800'],
        textDecorationColor: theme.vars.color.blue['800'],
      },
    },
    '[data-v-prompt-token="code"]': {
      borderRadius: theme.vars.borderRadius['sm'],
      backgroundColor: theme.vars.color.gray['100'],
      paddingInline: theme.vars.spacing[1],
      paddingBlock: 'calc(0.25rem * 0.5)',
      color: theme.vars.color.foreground,
      boxDecorationBreak: 'clone',
    },
    '[data-v-prompt-delimiter]': { color: theme.vars.color.gray['800'] },
    '[data-v-prompt-token="label"]': {
      fontWeight: theme.vars.fontWeight['medium'],
      color: theme.vars.color.foreground,
    },
    '[data-v-prompt-token="marker"]': { color: theme.vars.color.blue['900'] },
    '[data-v-prompt-token="placeholder"]': {
      borderRadius: theme.vars.borderRadius['sm'],
      backgroundColor: theme.vars.color.blue['300'],
      paddingInline: theme.vars.spacing[1],
      color: theme.vars.color.blue['800'],
      boxDecorationBreak: 'clone',
    },
    '[data-v-code-group-list]': {
      display: 'flex',
      alignItems: 'center',
      overflowX: 'auto',
      overflowY: 'hidden',
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      paddingInline: theme.vars.spacing[2],
      whiteSpace: 'nowrap',
      '@media (width < 48rem)': { paddingInline: theme.vars.spacing[1] },
      scrollbarWidth: 'thin',
      scrollbarGutter: 'stable',
    },
    '[data-v-code-group-list]::-webkit-scrollbar': { height: '4px' },
    '[data-v-code-group-list]::-webkit-scrollbar-track': { background: 'transparent' },
    '[data-v-code-group-list]::-webkit-scrollbar-thumb': {
      borderRadius: 'calc(infinity * 1px)',
      backgroundColor: theme.vars.color.gray['400'],
    },
    '[data-v-code-group-tab]': {
      marginBottom: 'calc(1.5px * -1)',
      height: '100%',
      borderBottomStyle: 'solid',
      borderBottomWidth: '1.5px',
      borderBottomColor: 'transparent',
      paddingInline: theme.vars.spacing[3],
      fontWeight: theme.vars.fontWeight['medium'],
      letterSpacing: '-0.025em',
      color: theme.vars.color.gray['900'],
      transitionProperty:
        'color, background-color, border-color, outline-color, text-decoration-color, fill, stroke',
      transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
      transitionDuration: '200ms',
      '&:hover': { '@media (hover: hover)': { color: theme.vars.color.foreground } },
      '&[data-active]': { color: theme.vars.color.foreground },
    },
    'pre[data-v] .line[data-v-collapse-trigger]': {
      position: 'relative',
      cursor: 'pointer',
      WebkitUserSelect: 'none',
      userSelect: 'none',
    },
    'pre[data-v] .line[data-v-collapse-trigger]:hover': {
      backgroundColor: theme.vars.color.surface,
    },
    'pre[data-v] [data-v-collapse-icon]': {
      position: 'absolute',
      top: theme.vars.spacing[0],
      left: theme.vars.spacing[1],
      display: 'inline-flex',
      height: theme.vars.spacing[4],
      width: theme.vars.spacing[4],
      translate: ' 0.35em',
      alignItems: 'center',
      justifyContent: 'center',
      color: theme.vars.color.gray['900'],
      transitionProperty: 'transform, translate, scale, rotate',
      transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
      transitionDuration: '200ms',
    },
    'pre[data-v] .line[data-v-collapse-trigger][data-v-collapsed=""] [data-v-collapse-icon]': {
      rotate: 'calc(90deg * -1)',
    },
    'pre[data-v] .line[data-v-collapse-trigger][data-v-collapsed="false"] [data-v-collapse-icon]': {
      rotate: '0deg',
    },
    '[data-v-fold-button]': {
      cursor: 'pointer',
      borderRadius: theme.vars.borderRadius['md'],
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      backgroundColor: theme.vars.color.surface,
      paddingInline: 'calc(0.25rem * 1.5)',
      paddingBlock: 'calc(0.25rem * 0.5)',
      fontFamily: theme.vars.fontFamily.mono,
      fontSize: theme.vars.fontSize['xs'],
      lineHeight: 'calc(1 / 0.75)',
      color: theme.vars.color.gray['900'],
      transitionProperty:
        'color, background-color, border-color, outline-color, text-decoration-color, fill, stroke',
      transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
      transitionDuration: '150ms',
      '&:hover': {
        backgroundColor: theme.vars.color.gray['100'],
        color: theme.vars.color.foreground,
      },
    },
    'pre[data-v-shell]': {
      '& .line[data-v-shell-line]': { position: 'relative' },
      '& [data-v-shell-prompt]': { opacity: '50%', WebkitUserSelect: 'none', userSelect: 'none' },
      '& [data-v-shell-copy]': {
        position: 'absolute',
        top: 'calc(1 / 2 * 100%)',
        right: 'calc(0.25rem * 2.5)',
        translate: ' calc(calc(1 / 2 * 100%) * -1)',
        cursor: 'pointer',
        borderRadius: theme.vars.borderRadius['md'],
        padding: theme.vars.spacing[1],
        color: theme.vars.color.gray['900'],
        opacity: '0%',
        transitionProperty: 'opacity',
        transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
        transitionDuration: '150ms',
        '&:hover': { '@media (hover: hover)': { color: theme.vars.color.foreground } },
      },
      '& .line[data-v-shell-line]:hover [data-v-shell-copy], & [data-v-shell-copy]:focus, & [data-v-shell-copy][data-copied="true"]':
        { opacity: '100%' },
      '& [data-v-shell-copy][data-copied="true"]': { color: theme.vars.color.green['900'] },
    },
    ':not(pre) > code[data-v]:not(.twoslash-popup-code)': {
      borderRadius: theme.vars.borderRadius['sm'],
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      backgroundColor: theme.vars.color.gray['100'],
      paddingInline: 'calc(0.25rem * 1.5)',
      paddingBlock: 'calc(0.25rem * 0.5)',
      fontSize: '0.875em',
      fontWeight: theme.vars.fontWeight['medium'],
    },
    '[data-v-context="note"] code[data-v]': {
      '&&': {
        borderColor: theme.vars.color.gray['400'],
        backgroundColor: `${theme.vars.color.gray[100]} !important`,
        '@supports (color: color-mix(in lab, red, red))': {
          backgroundColor: `color-mix(in oklab, ${theme.vars.color.gray['100']} 60%, transparent) !important`,
        },
      },
    },
    '[data-v-context="info"] code[data-v]': {
      '&&': {
        borderColor: theme.vars.color.blue['400'],
        backgroundColor: `${theme.vars.color.gray[100]} !important`,
        '@supports (color: color-mix(in lab, red, red))': {
          backgroundColor: `color-mix(in oklab, ${theme.vars.color.gray['100']} 60%, transparent) !important`,
        },
      },
    },
    '[data-v-context="warning"] code[data-v]': {
      '&&': {
        borderColor: theme.vars.color.amber['400'],
        backgroundColor: `${theme.vars.color.gray[100]} !important`,
        '@supports (color: color-mix(in lab, red, red))': {
          backgroundColor: `color-mix(in oklab, ${theme.vars.color.gray['100']} 60%, transparent) !important`,
        },
      },
    },
    '[data-v-context="danger"] code[data-v]': {
      '&&': {
        borderColor: theme.vars.color.red['400'],
        backgroundColor: `${theme.vars.color.gray[100]} !important`,
        '@supports (color: color-mix(in lab, red, red))': {
          backgroundColor: `color-mix(in oklab, ${theme.vars.color.gray['100']} 60%, transparent) !important`,
        },
      },
    },
    '[data-v-context="tip"] :is(code[data-v], span.shiki)': {
      '&&': {
        borderColor: theme.vars.color.purple['400'],
        backgroundColor: `${theme.vars.color.gray[100]} !important`,
        '@supports (color: color-mix(in lab, red, red))': {
          backgroundColor: `color-mix(in oklab, ${theme.vars.color.gray['100']} 60%, transparent) !important`,
        },
      },
    },
    '[data-v-context="success"] :is(code[data-v], span.shiki)': {
      '&&': {
        borderColor: theme.vars.color.green['400'],
        backgroundColor: `${theme.vars.color.gray[100]} !important`,
        '@supports (color: color-mix(in lab, red, red))': {
          backgroundColor: `color-mix(in oklab, ${theme.vars.color.gray['100']} 60%, transparent) !important`,
        },
      },
    },
    '[data-v-steps]': {
      marginLeft: theme.vars.spacing[3],
      borderLeftStyle: 'solid',
      borderLeftWidth: '1.5px',
      borderLeftColor: theme.vars.color.gray['400'],
      paddingLeft: theme.vars.spacing[6],
      '@media (width < 48rem)': { marginLeft: theme.vars.spacing[1] },
      counterReset: 'step',
      ':where(& > :not(:last-child))': {
        marginBlockStart: 'calc(calc(0.25rem * 6) * 0)',
        marginBlockEnd: 'calc(calc(0.25rem * 6) * calc(1 - 0))',
        borderLeftStyle: 'solid',
      },
    },
    '[data-v-step-title]': {
      position: 'relative',
      marginTop: theme.vars.spacing[6],
      display: 'flex',
      scrollMarginTop: 'calc(var(--vocs-layout-topNav) + 0.5rem) !important',
      alignItems: 'center',
      padding: theme.vars.spacing[0],
      '&::before': { content: '""', counterIncrement: 'step' },
    },
    ':is(h1, h2, h3, h4, h5, h6)[data-v-step-title]': {
      fontWeight: theme.vars.fontWeight['medium'],
    },
    '[data-v-step-content]': {
      marginTop: 'calc(0.25rem * -2)',
      ':where(& > :not(:last-child))': {
        marginBlockStart: 'calc(calc(0.25rem * 6) * 0)',
        marginBlockEnd: 'calc(calc(0.25rem * 6) * calc(1 - 0))',
      },
    },
    '[data-v-mermaid-container]': { marginBlock: theme.vars.spacing[6] },
    '[data-v-mermaid]': { display: 'flex', justifyContent: 'center', overflowX: 'auto' },
    '[data-v-mermaid] svg': { height: 'auto', maxWidth: '100%' },
    '[data-v-mermaid-loading]': {
      paddingBlock: theme.vars.spacing[8],
      textAlign: 'center',
      color: theme.vars.color.gray['900'],
    },
    '[data-v-mermaid-error]': {
      borderRadius: theme.vars.borderRadius['lg'],
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: theme.vars.color.red['400'],
      backgroundColor: theme.vars.color.red['100'],
      padding: theme.vars.spacing[4],
      color: theme.vars.color.red['900'],
    },
    '[data-v-mermaid-error] pre': {
      margin: theme.vars.spacing[0],
      fontSize: theme.vars.fontSize['sm'],
      lineHeight: 'calc(1.25 / 0.875)',
      whiteSpace: 'pre-wrap',
    },
    '[data-v-changelog] div[data-v-table-wrapper]': {
      marginInline: 'calc(0.25rem * 0) !important',
      '@media (width < 48rem)': { marginInline: 'calc(0.25rem * 0) !important' },
    },
    '[data-v-changelog-release]': { contentVisibility: 'auto', containIntrinsicSize: 'auto 400px' },
    '@layer properties': {
      '@supports ((-webkit-hyphens: none) and (not (margin-trim: inline))) or ((-moz-orient: inline) and (not (color:rgb(from red r g b))))':
        { '*, ::before, ::after, ::backdrop': {} },
    },
  },
})
