import { theme } from 'zyzz/default'
import { global } from 'zyzz/web'

global({
  '@layer vocs_components': {
    '[data-v-sidebar-item-badge]': {
      paddingInline: 'calc(0.25rem * 1.5)',
      paddingBlock: 'calc(0.25rem * 0.5)',
      fontSize: '10px',
    },
    '[data-v-sidebar-item-badge][data-v-icon]': {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    '[data-v-sidebar-item-badge-icon]': {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    '[data-v-sidebar-item-badge-icon] svg': {
      width: theme.vars.spacing[3],
      height: theme.vars.spacing[3],
    },
    '[data-v-openapi]': { display: 'flex', flexDirection: 'column', gap: theme.vars.spacing[6] },
    '[data-v-openapi-landing]': { maxWidth: 'var(--vocs-layout-content)' },
    '[data-v-openapi-group]': {
      display: 'flex',
      flexDirection: 'column',
      gap: theme.vars.spacing[2],
      paddingTop: theme.vars.spacing[6],
    },
    '[data-v-openapi-header]': {
      display: 'flex',
      maxWidth: 'var(--vocs-layout-content)',
      flexDirection: 'column',
      borderBottomStyle: 'solid',
      borderBottomWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      paddingBottom: '0.75em',
      fontSize: theme.vars.fontSize['4xl'],
    },
    '[data-v-openapi-h1], [data-v-openapi-h2]': { marginTop: 'calc(0.25rem * 0) !important' },
    '[data-v-openapi-info-title]': { marginTop: 'calc(0.25rem * 0) !important' },
    '[data-v-openapi-description]': {
      marginTop: '0.25em',
      fontSize: theme.vars.fontSize['lg'],
      lineHeight: '1.5em',
      fontWeight: theme.vars.fontWeight['medium'],
      color: theme.vars.color.gray['900'],
    },
    '[data-v-openapi-overview]': {
      display: 'flex',
      flexDirection: 'column',
      overflow: 'hidden',
      borderRadius: theme.vars.borderRadius['md'],
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      backgroundColor: theme.vars.color.gray['100'],
      '@supports (color: color-mix(in lab, red, red))': {
        backgroundColor: `color-mix(in oklab, ${theme.vars.color.gray['100']} 70%, transparent)`,
      },
      paddingInline: theme.vars.spacing[4],
    },
    '[data-v-openapi-overview-category]': {
      borderTopStyle: 'solid',
      borderTopWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
    },
    '[data-v-openapi-overview-category]:first-child': {
      borderTopStyle: 'solid',
      borderTopWidth: '0px',
    },
    '[data-v-openapi-overview] [data-v-openapi-disclosure-trigger]': {
      display: 'flex',
      cursor: 'pointer',
      alignItems: 'center',
      gap: theme.vars.spacing[2],
      paddingBlock: theme.vars.spacing[3],
      textAlign: 'left',
      marginInline: 'calc(0.25rem * -4)',
      width: 'calc(100% + 2rem)',
      paddingInline: theme.vars.spacing[4],
      transitionProperty:
        'color, background-color, border-color, outline-color, text-decoration-color, fill, stroke',
      transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
      transitionDuration: '150ms',
    },
    '[data-v-openapi-overview] [data-v-openapi-disclosure-trigger]:hover': {
      backgroundColor: theme.vars.color.gray['100'],
    },
    '[data-v-openapi-overview-chevron]': {
      width: theme.vars.spacing[4],
      height: theme.vars.spacing[4],
      flexShrink: 0,
      color: theme.vars.color.gray['900'],
      transitionProperty: 'transform, translate, scale, rotate',
      transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
      transitionDuration: '150ms',
    },
    '[data-v-openapi-disclosure-trigger][data-panel-open] [data-v-openapi-overview-chevron]': {
      rotate: '90deg',
    },
    '[data-v-openapi-overview-category-head]': {
      display: 'flex',
      minWidth: theme.vars.spacing[0],
      flex: 1,
      flexDirection: 'column',
      gap: 'calc(0.25rem * 0.5)',
    },
    '[data-v-openapi-overview-category-name]': {
      fontWeight: theme.vars.fontWeight['medium'],
      color: theme.vars.color.foreground,
    },
    '[data-v-openapi-overview-category-description]': {
      fontSize: '13px',
      color: theme.vars.color.gray['900'],
    },
    '[data-v-openapi-overview] [data-v-openapi-disclosure-panel]': {
      paddingTop: theme.vars.spacing[1],
      paddingBottom: theme.vars.spacing[3],
    },
    '[data-v-openapi-overview-endpoints]': {
      display: 'flex',
      flexDirection: 'column',
      gap: theme.vars.spacing[2],
    },
    '[data-v-openapi-overview-resource]': {
      margin: theme.vars.spacing[0],
      listStyleType: 'none',
      padding: theme.vars.spacing[0],
    },
    '[data-v-openapi-overview-resource] > li': {
      margin: theme.vars.spacing[0],
      padding: theme.vars.spacing[0],
    },
    '[data-v-openapi-overview-endpoint]': {
      display: 'flex',
      alignItems: 'center',
      gap: theme.vars.spacing[3],
      borderRadius: theme.vars.borderRadius['lg'],
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      backgroundColor: theme.vars.color.background['200'],
      paddingInline: theme.vars.spacing[3],
      paddingBlock: theme.vars.spacing[2],
    },
    '[data-v-openapi-overview-endpoint]:hover': {
      backgroundColor: theme.vars.color.gray['100'],
    },
    '[data-v-openapi-overview-endpoint-title]': {
      minWidth: theme.vars.spacing[0],
      flex: 1,
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
      fontSize: '14px',
      color: theme.vars.color.foreground,
    },
    '[data-v-openapi-overview-endpoint-chevron]': {
      width: theme.vars.spacing[4],
      height: theme.vars.spacing[4],
      flexShrink: 0,
      color: theme.vars.color.gray['900'],
    },
    '[data-v-openapi] [data-v-content]': { marginLeft: 'unset', marginRight: 'unset' },
    '[data-v-openapi-intro]': {
      maxWidth: 'var(--vocs-layout-content)',
      ':where(& > :not(:last-child))': {
        marginBlockStart: 'calc(calc(0.25rem * 6) * 0)',
        marginBlockEnd: 'calc(calc(0.25rem * 6) * calc(1 - 0))',
      },
    },
    '[data-v-openapi-guide]': {
      maxWidth: 'var(--vocs-layout-content)',
      ':where(& > :not(:last-child))': {
        marginBlockStart: 'calc(calc(0.25rem * 6) * 0)',
        marginBlockEnd: 'calc(calc(0.25rem * 6) * calc(1 - 0))',
      },
    },
    '[data-v-openapi-operation]': {
      display: 'grid',
      rowGap: '2rem',
      columnGap: '4rem',
      gridTemplateColumns: 'minmax(0, 1fr)',
      gridTemplateAreas: '"header" "aside" "body"',
    },
    '[data-v-openapi-operation][data-separator]': {
      marginTop: theme.vars.spacing[20],
      borderTopStyle: 'solid',
      borderTopWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      paddingTop: theme.vars.spacing[20],
    },
    '[data-v-openapi-operation]:not([data-separator])': { paddingTop: theme.vars.spacing[8] },
    '[data-v-openapi-operation-header]': {
      gridArea: 'header',
      display: 'flex',
      minWidth: theme.vars.spacing[0],
      flexDirection: 'column',
      gap: theme.vars.spacing[3],
    },
    '[data-v-openapi-operation-body]': {
      gridArea: 'body',
      display: 'flex',
      minWidth: theme.vars.spacing[0],
      flexDirection: 'column',
      gap: theme.vars.spacing[8],
    },
    '[data-v-openapi-operation-aside]': {
      gridArea: 'aside',
      top: 'calc(var(--vocs-layout-topNav) + var(--vocs-layout-banner) + 1rem)',
      display: 'flex',
      minWidth: theme.vars.spacing[0],
      flexDirection: 'column',
      alignSelf: 'flex-start',
      '@media (width >= 64rem)': { overflow: 'hidden' },
    },
    '@media (min-width: 64rem)': {
      '[data-v-openapi-operation]': {
        gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)',
        gridTemplateAreas: '"header aside" "body aside"',
        alignItems: 'start',
      },
    },
    '[data-v-openapi-operation-title]': {
      marginTop: 'calc(0.25rem * 0) !important',
      display: 'flex',
      scrollMarginTop: 'calc(0.25rem * 0) !important',
      alignItems: 'center',
      gap: theme.vars.spacing[2],
    },
    '[data-v-openapi-endpoint]': {
      display: 'flex',
      alignItems: 'center',
      gap: theme.vars.spacing[3],
      borderRadius: theme.vars.borderRadius['lg'],
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      backgroundColor: theme.vars.color.background['200'],
      paddingInline: theme.vars.spacing[3],
      paddingBlock: theme.vars.spacing[2],
    },
    '[data-v-openapi-endpoint-path]': {
      paddingInline: 'calc(0.25rem * 0) !important',
      fontSize: '13px',
      wordBreak: 'break-all',
      color: theme.vars.color.gray['900'],
    },
    '[data-v-openapi-prose]': { fontSize: '15px', color: theme.vars.color.gray['900'] },
    '[data-v-openapi-section]': {
      display: 'flex',
      flexDirection: 'column',
      gap: theme.vars.spacing[3],
    },
    '[data-v-openapi-section-title]': {
      display: 'flex',
      alignItems: 'center',
      gap: theme.vars.spacing[2],
    },
    '[data-v-openapi-params], [data-v-openapi-schema], [data-v-openapi-responses]': {
      display: 'flex',
      flexDirection: 'column',
    },
    '[data-v-openapi-children]': {
      borderLeftStyle: 'solid',
      borderLeftWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      paddingLeft: theme.vars.spacing[4],
    },
    '[data-v-openapi-content]': {
      display: 'flex',
      flexDirection: 'column',
      gap: theme.vars.spacing[3],
    },
    '[data-v-openapi-media]': {
      display: 'flex',
      flexDirection: 'column',
      gap: theme.vars.spacing[2],
    },
    '[data-v-openapi-media-type]': { fontSize: '12px', color: theme.vars.color.gray['900'] },
    '[data-v-openapi-variant]': {
      display: 'flex',
      flexDirection: 'column',
      gap: theme.vars.spacing[2],
    },
    '[data-v-openapi-property]': {
      display: 'flex',
      flexDirection: 'column',
      gap: 'calc(0.25rem * 1.5)',
      paddingBlock: theme.vars.spacing[3],
    },
    '[data-v-openapi-property-head]': {
      display: 'flex',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: theme.vars.spacing[2],
    },
    '[data-v-openapi-property-name]': { fontFamily: theme.vars.fontFamily.mono, fontSize: '13px' },
    '[data-v-openapi-property-prefix]': {
      fontWeight: theme.vars.fontWeight['normal'],
      color: theme.vars.color.gray['900'],
    },
    '[data-v-openapi-property-label]': {
      fontWeight: theme.vars.fontWeight['semibold'],
      color: theme.vars.color.foreground,
    },
    '[data-v-openapi-property-required]': {
      paddingInline: 'calc(0.25rem * 1.5) !important',
      paddingBlock: 'calc(0.25rem * 0.5) !important',
      fontSize: '10px !important',
    },
    '[data-v-openapi-property-head] .heading-anchor': {
      marginLeft: 'calc(0.25rem * 0) !important',
    },
    '[data-v-openapi-property]:hover .heading-anchor': { opacity: '100%' },
    '[data-v-openapi-property-meta]': {
      display: 'flex',
      flexWrap: 'wrap',
      alignItems: 'center',
      columnGap: theme.vars.spacing[2],
      rowGap: 'calc(0.25rem * 0.5)',
      fontFamily: theme.vars.fontFamily.mono,
      fontSize: '12px',
    },
    '[data-v-openapi-type]': { fontSize: '12px !important' },
    '[data-v-openapi-meta-label], [data-v-openapi-meta-sep]': {
      color: theme.vars.color.gray['900'],
    },
    '[data-v-openapi-meta-value]': { color: theme.vars.color.foreground },
    '[data-v-openapi-property-description]': {
      fontSize: '13px',
      color: theme.vars.color.gray['900'],
    },
    '[data-v-openapi-property-example]': {
      display: 'flex',
      flexDirection: 'column',
      fontSize: '12px',
    },
    '[data-v-openapi-property-example-label]': { color: theme.vars.color.gray['900'] },
    '[data-v-openapi-property-example-value]': {
      textAlign: 'left',
      fontFamily: theme.vars.fontFamily.mono,
      wordBreak: 'break-all',
      whiteSpace: 'pre-wrap',
      color: theme.vars.color.foreground,
    },
    'button[data-v-openapi-property-example-value]': {
      cursor: 'pointer',
      textDecorationLine: 'underline',
      textDecorationStyle: 'dotted',
      textUnderlineOffset: '2px',
      transitionProperty:
        'color, background-color, border-color, outline-color, text-decoration-color, fill, stroke',
      transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
      transitionDuration: '150ms',
      textDecorationColor: theme.vars.color.gray['900'],
    },
    'button[data-v-openapi-property-example-value]:hover': {
      textDecorationColor: theme.vars.color.foreground,
    },
    '[data-v-openapi-property]:target, [data-v-openapi-property][data-v-openapi-flash]': {
      borderRadius: theme.vars.borderRadius['xs'],
      animation: 'vocs-openapi-target-flash 1.6s ease-out',
    },
    ':root': {
      '--vocs-openapi-flash-bg': theme.vars.color.blue['200'],
    },
    '[data-v-openapi-values]': { display: 'flex', flexDirection: 'column' },
    '[data-v-openapi-values-label]': { fontSize: '12px', color: theme.vars.color.gray['900'] },
    '[data-v-openapi-values-list]': {
      display: 'flex',
      flexDirection: 'column',
      borderLeftStyle: 'solid',
      borderLeftWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      paddingLeft: theme.vars.spacing[3],
    },
    '[data-v-openapi-values-item]': {
      paddingInline: 'calc(0.25rem * 0) !important',
      fontFamily: theme.vars.fontFamily.mono,
      fontSize: '12.5px',
      wordBreak: 'break-all',
      color: theme.vars.color.foreground,
    },
    '[data-v-openapi-disclosure]': { width: '100%' },
    '[data-v-openapi-disclosure-header]': {
      margin: 'calc(0.25rem * 0) !important',
      padding: 'calc(0.25rem * 0) !important',
    },
    '[data-v-openapi-pill], [data-v-openapi-collapse] [data-v-openapi-disclosure-header] [data-v-openapi-disclosure-trigger]':
      {
        display: 'inline-flex',
        width: 'fit-content',
        alignItems: 'center',
        gap: 'calc(0.25rem * 1.5)',
        borderRadius: theme.vars.borderRadius['md'],
        borderStyle: 'solid',
        borderWidth: '1px',
        borderColor: theme.vars.color.gray['400'],
        paddingInline: theme.vars.spacing[2],
        paddingBlock: 'calc(0.25rem * 0.5)',
        fontSize: '12px',
        fontWeight: theme.vars.fontWeight['medium'],
        color: theme.vars.color.gray['900'],
        transitionProperty:
          'color, background-color, border-color, outline-color, text-decoration-color, fill, stroke',
        transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
        transitionDuration: '150ms',
      },
    '[data-v-openapi-pill]:hover, [data-v-openapi-collapse] [data-v-openapi-disclosure-trigger]:hover':
      { backgroundColor: theme.vars.color.gray['100'], color: theme.vars.color.foreground },
    '[data-v-openapi-values] [data-v-openapi-pill]': { marginTop: theme.vars.spacing[2] },
    '[data-v-openapi-pill-icon], [data-v-openapi-collapse-icon-show], [data-v-openapi-collapse-icon-hide]':
      { width: theme.vars.spacing[3], height: theme.vars.spacing[3] },
    '[data-v-openapi-collapse] [data-v-openapi-disclosure-panel]': {
      marginTop: theme.vars.spacing[2],
    },
    '[data-v-openapi-collapse-icon-hide], [data-v-openapi-collapse-label-hide]': {
      display: 'none',
    },
    '[data-v-openapi-disclosure-trigger][data-panel-open] [data-v-openapi-collapse-icon-show], [data-v-openapi-disclosure-trigger][data-panel-open] [data-v-openapi-collapse-label-show]':
      { display: 'none' },
    '[data-v-openapi-disclosure-trigger][data-panel-open] [data-v-openapi-collapse-icon-hide], [data-v-openapi-disclosure-trigger][data-panel-open] [data-v-openapi-collapse-label-hide]':
      { display: 'inline' },
    '[data-v-openapi-response]': {
      borderTopStyle: 'solid',
      borderTopWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
    },
    '[data-v-openapi-response]:first-child': { borderTopStyle: 'solid', borderTopWidth: '0px' },
    '[data-v-openapi-response][data-static]': {
      display: 'flex',
      alignItems: 'center',
      gap: theme.vars.spacing[2],
      paddingBlock: theme.vars.spacing[2],
    },
    '[data-v-openapi-response] [data-v-openapi-disclosure-trigger]': {
      display: 'flex',
      width: '100%',
      cursor: 'pointer',
      alignItems: 'center',
      gap: theme.vars.spacing[2],
      paddingBlock: theme.vars.spacing[2],
      textAlign: 'left',
    },
    '[data-v-openapi-response] [data-v-openapi-disclosure-panel]': {
      paddingBottom: theme.vars.spacing[3],
    },
    '[data-v-openapi-response-chevron]': {
      width: theme.vars.spacing[4],
      height: theme.vars.spacing[4],
      flexShrink: 0,
      color: theme.vars.color.gray['900'],
      transitionProperty: 'transform, translate, scale, rotate',
      transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
      transitionDuration: '150ms',
    },
    '[data-v-openapi-disclosure-trigger][data-panel-open] [data-v-openapi-response-chevron]': {
      rotate: '90deg',
    },
    '[data-v-openapi-response-spacer]': {
      width: theme.vars.spacing[4],
      height: theme.vars.spacing[4],
      flexShrink: 0,
    },
    '[data-v-openapi-response-status]': { flexShrink: 0 },
    '[data-v-openapi-response-description]': {
      minWidth: theme.vars.spacing[0],
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
      fontSize: '13px',
      color: theme.vars.color.gray['900'],
    },
    '[data-v-openapi-response-content]': {
      display: 'flex',
      flexDirection: 'column',
      gap: theme.vars.spacing[3],
    },
    '[data-v-openapi-example]': {
      overflow: 'auto',
      borderRadius: theme.vars.borderRadius['lg'],
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      padding: theme.vars.spacing[3],
      fontSize: '12px',
    },
    '[data-v-openapi-sample]': {
      display: 'flex',
      maxHeight: '100%',
      minHeight: theme.vars.spacing[0],
      flexDirection: 'column',
      overflow: 'hidden',
      borderRadius: theme.vars.borderRadius['lg'],
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
    },
    '[data-v-openapi-sample-request]': { display: 'flex', flexShrink: 0, flexDirection: 'column' },
    '[data-v-openapi-sample-header]': {
      display: 'flex',
      height: theme.vars.spacing[10],
      alignItems: 'center',
      borderBottomStyle: 'solid',
      borderBottomWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      backgroundColor: theme.vars.color.surface,
      paddingInline: theme.vars.spacing[3],
    },
    '[data-v-openapi-sample-actions]': {
      marginLeft: 'auto',
      display: 'flex',
      alignItems: 'center',
      gap: 'calc(0.25rem * 1.5)',
    },
    '[data-v-openapi-sample-response]': {
      display: 'flex',
      minHeight: theme.vars.spacing[0],
      flex: 1,
      flexDirection: 'column',
      borderTopStyle: 'solid',
      borderTopWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
    },
    '[data-v-openapi-sample-tabs]': {
      display: 'flex',
      flexShrink: 0,
      flexWrap: 'wrap',
      alignItems: 'stretch',
      borderBottomStyle: 'solid',
      borderBottomWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      backgroundColor: theme.vars.color.surface,
      paddingInline: theme.vars.spacing[3],
    },
    '[data-v-openapi-sample-response-body]': {
      minHeight: theme.vars.spacing[0],
      flex: 1,
      overflowY: 'auto',
    },
    '[data-v-openapi-sample] pre.shiki': {
      overflowX: 'auto',
      backgroundColor: theme.vars.color.background['200'],
      paddingBlock: theme.vars.spacing[4],
    },
    '[data-v-openapi-sample] pre.shiki > code': { display: 'grid', fontSize: '0.875em' },
    '[data-v-openapi-sample] pre.shiki > code > .line': {
      paddingInline: 'var(--vocs-layout-code-block-px)',
      lineHeight: '1.75em',
    },
    '[data-v-openapi-sample] [data-v-openapi-placeholder]': { opacity: '45%' },
    '[data-v-openapi-sample] pre.shiki > code > .line[data-anchor]': { cursor: 'pointer' },
    '[data-v-openapi-sample] pre.shiki > code > .line[data-anchor]:hover': {
      backgroundColor: theme.vars.color.gray['200'],
    },
    '[data-v-openapi-sample] pre.shiki > code > .line[data-v-openapi-flash], [data-v-openapi-sample] [data-v-openapi-anchor][data-v-openapi-flash]':
      { animation: 'vocs-openapi-line-flash 1.6s ease-out' },
    '[data-v-openapi-sample] [data-v-openapi-anchor][data-v-openapi-flash]': {
      borderRadius: theme.vars.borderRadius['xs'],
    },
    '[data-v-openapi-sample] [data-v-openapi-token="key"]': {
      color: 'var(--vocs-openapi-token-key) !important',
    },
    '[data-v-openapi-sample] [data-v-openapi-token="value"]': {
      color: 'var(--vocs-openapi-token-value) !important',
    },
    '[data-v-openapi-sample] [data-v-openapi-anchor]': {
      cursor: 'pointer',
      borderRadius: theme.vars.borderRadius['xs'],
    },
    '[data-v-openapi-sample] [data-v-openapi-anchor]:hover': {
      backgroundColor: theme.vars.color.gray['200'],
    },
    '[data-v-openapi-sample-more]': {
      marginTop: 'calc(0.25rem * -2)',
      display: 'flex',
      width: '100%',
      cursor: 'pointer',
      alignItems: 'center',
      gap: 'calc(0.25rem * 1.5)',
      backgroundColor: theme.vars.color.background['200'],
      paddingInline: 'var(--vocs-layout-code-block-px)',
      paddingBottom: theme.vars.spacing[3],
      fontSize: '12px',
      fontWeight: theme.vars.fontWeight['medium'],
      color: theme.vars.color.gray['900'],
    },
    '[data-v-openapi-sample-more]:hover': { color: theme.vars.color.foreground },
    '[data-v-openapi-sample-more-icon]': {
      width: 'calc(0.25rem * 3.5)',
      height: 'calc(0.25rem * 3.5)',
    },
    '[data-v-openapi-action]': {
      display: 'inline-flex',
      cursor: 'pointer',
      alignItems: 'center',
      gap: 'calc(0.25rem * 1.5)',
      borderRadius: theme.vars.borderRadius['md'],
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      paddingInline: theme.vars.spacing[2],
      paddingBlock: 'calc(0.25rem * 0.5)',
      fontSize: '12px',
      fontWeight: theme.vars.fontWeight['medium'],
    },
    '[data-v-openapi-action]:disabled': { cursor: 'default', opacity: '50%' },
    '[data-v-openapi-action-icon]': {
      width: theme.vars.spacing[3],
      height: theme.vars.spacing[3],
      color: theme.vars.color.gray['800'],
    },
    '[data-v-openapi-action-icon][data-copied]': { color: theme.vars.color.blue['900'] },
    '[data-v-openapi-tab]': {
      marginBottom: 'calc(1.5px * -1)',
      display: 'flex',
      height: theme.vars.spacing[10],
      cursor: 'pointer',
      alignItems: 'center',
      borderBottomStyle: 'solid',
      borderBottomWidth: '1.5px',
      borderBottomColor: 'transparent',
      paddingInline: theme.vars.spacing[3],
      fontSize: '13px',
      fontWeight: theme.vars.fontWeight['medium'],
      letterSpacing: '-0.025em',
      transitionProperty:
        'color, background-color, border-color, outline-color, text-decoration-color, fill, stroke',
      transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
      transitionDuration: '150ms',
    },
    '[data-v-openapi-tab]:not([data-active])': { color: theme.vars.color.gray['900'] },
    '[data-v-openapi-tab]:not([data-active]):hover': { color: theme.vars.color.foreground },
    '[data-v-openapi-tab][data-active]': {
      borderBottomColor: theme.vars.color.foreground,
      color: theme.vars.color.foreground,
    },
    '[data-v-openapi-lang-label]': {
      fontSize: '13px',
      fontWeight: theme.vars.fontWeight['medium'],
      letterSpacing: '-0.025em',
      color: theme.vars.color.foreground,
    },
    '[data-v-openapi-lang]': { position: 'relative' },
    '[data-v-openapi-lang-trigger]': {
      display: 'flex',
      cursor: 'pointer',
      alignItems: 'center',
      gap: theme.vars.spacing[1],
      fontSize: '13px',
      fontWeight: theme.vars.fontWeight['medium'],
      letterSpacing: '-0.025em',
      color: theme.vars.color.foreground,
    },
    '[data-v-openapi-lang-chevron], [data-v-openapi-union-chevron]': {
      width: theme.vars.spacing[4],
      height: theme.vars.spacing[4],
      color: theme.vars.color.gray['900'],
    },
    '[data-v-openapi-dropdown-backdrop]': {
      position: 'fixed',
      inset: theme.vars.spacing[0],
      zIndex: 10,
      cursor: 'default',
    },
    '[data-v-openapi-lang-menu]': {
      position: 'absolute',
      top: '100%',
      left: theme.vars.spacing[0],
      zIndex: 20,
      marginTop: theme.vars.spacing[1],
      minWidth: theme.vars.spacing[36],
      overflow: 'auto',
      borderRadius: theme.vars.borderRadius['md'],
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      backgroundColor: theme.vars.color.surface,
      paddingBlock: theme.vars.spacing[1],
      boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
    },
    '[data-v-openapi-lang-option], [data-v-openapi-union-option]': {
      display: 'flex',
      width: '100%',
      cursor: 'pointer',
      alignItems: 'center',
      gap: theme.vars.spacing[2],
      paddingInline: theme.vars.spacing[3],
      paddingBlock: 'calc(0.25rem * 1.5)',
      textAlign: 'left',
      fontSize: '13px',
    },
    '[data-v-openapi-lang-option]:hover, [data-v-openapi-union-option]:hover': {
      backgroundColor: theme.vars.color.gray['100'],
    },
    '[data-v-openapi-lang-option-check]': {
      width: 'calc(0.25rem * 3.5)',
      height: 'calc(0.25rem * 3.5)',
      flexShrink: 0,
      opacity: '0%',
    },
    '[data-v-openapi-lang-option][data-selected] [data-v-openapi-lang-option-check]': {
      color: theme.vars.color.blue['900'],
      opacity: '100%',
    },
    '[data-v-openapi-lang-option-label], [data-v-openapi-union-option-label]': {
      color: theme.vars.color.gray['900'],
    },
    '[data-v-openapi-lang-option][data-selected] [data-v-openapi-lang-option-label], [data-v-openapi-union-option][data-selected] [data-v-openapi-union-option-label]':
      { color: theme.vars.color.foreground },
    '[data-v-openapi-union]': {
      display: 'flex',
      flexDirection: 'column',
      borderRadius: theme.vars.borderRadius['md'],
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
    },
    '[data-v-openapi-union-head]': { position: 'relative' },
    '[data-v-openapi-union-trigger]': {
      display: 'flex',
      width: '100%',
      cursor: 'pointer',
      alignItems: 'center',
      gap: 'calc(0.25rem * 1.5)',
      paddingInline: theme.vars.spacing[3],
      paddingBlock: theme.vars.spacing[2],
      fontSize: '13px',
    },
    '[data-v-openapi-union-kind]': { color: theme.vars.color.gray['900'] },
    '[data-v-openapi-union-value]': {
      fontWeight: theme.vars.fontWeight['medium'],
      color: theme.vars.color.foreground,
    },
    '[data-v-openapi-union-menu]': {
      position: 'absolute',
      top: '100%',
      left: theme.vars.spacing[0],
      zIndex: 20,
      marginTop: theme.vars.spacing[1],
      maxHeight: theme.vars.spacing[80],
      width: '100%',
      overflow: 'auto',
      borderRadius: theme.vars.borderRadius['md'],
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      backgroundColor: theme.vars.color.surface,
      paddingBlock: theme.vars.spacing[1],
      boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
    },
    '[data-v-openapi-union-radio]': {
      display: 'flex',
      width: theme.vars.spacing[4],
      height: theme.vars.spacing[4],
      flexShrink: 0,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 'calc(infinity * 1px)',
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
    },
    '[data-v-openapi-union-option][data-selected] [data-v-openapi-union-radio]': {
      borderColor: theme.vars.color.blue['700'],
    },
    '[data-v-openapi-union-radio-dot]': {
      width: theme.vars.spacing[2],
      height: theme.vars.spacing[2],
      borderRadius: 'calc(infinity * 1px)',
      backgroundColor: theme.vars.color.blue['700'],
    },
    '[data-v-openapi-union-panel][data-visible]': {
      borderTopStyle: 'solid',
      borderTopWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      paddingInline: theme.vars.spacing[3],
      paddingBlock: theme.vars.spacing[2],
    },
    '@media (width >= 1376px)': {
      '[data-v-content-width="full"]:has([data-v-openapi-landing], [data-v-openapi-guide]) [data-v-gutter-right]':
        {
          right: 'auto !important',
          left: 'calc(var(--vocs-layout-sidebar) + var(--vocs-layout-content-px) + var(--vocs-layout-content) + 2rem)',
        },
    },
    '[data-v-content-width="full"]:has([data-v-openapi-landing], [data-v-openapi-guide]) [data-v-content-footer]':
      { maxWidth: 'var(--vocs-layout-content)' },
    '[data-v-content-width="full"]:has([data-v-openapi-landing], [data-v-openapi-guide]) [data-v-footer]':
      { maxWidth: 'var(--vocs-layout-content) !important' },
    '@layer properties': {
      '@supports ((-webkit-hyphens: none) and (not (margin-trim: inline))) or ((-moz-orient: inline) and (not (color:rgb(from red r g b))))':
        { '*, ::before, ::after, ::backdrop': {} },
    },
  },
})
