import { theme } from 'zyzz/default'
import { global } from 'zyzz/web'

global({
  '@layer vocs_components': {
    '.twoslash': {
      '& [data-v-twoslash-trigger] span': {
        borderBottomStyle: 'dotted',
        borderBottomWidth: '1px',
        borderStyle: 'dotted',
        borderColor: 'transparent',
        transitionProperty:
          'color, background-color, border-color, outline-color, text-decoration-color, fill, stroke',
        transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
        transitionDuration: '200ms',
      },
      '&:hover [data-v-twoslash-trigger] span': { borderColor: 'inherit' },
      '&:hover [data-v-twoslash-trigger]': {
        cursor: 'text !important',
        WebkitUserSelect: 'text',
        userSelect: 'text',
      },
      '& .twoslash-error-line': {
        position: 'relative',
        marginBlock: theme.vars.spacing[1],
        width: 'max-content',
        minWidth: '100%',
        borderColor: theme.vars.color.red['400'],
        backgroundColor: theme.vars.color.red['100'],
        paddingInline: 'var(--vocs-layout-code-block-px)',
        paddingBlock: 'calc(0.25rem * 0.5)',
        lineHeight: '1.75em',
        color: theme.vars.color.red['900'],
      },
      '& .twoslash-completion-cursor': { position: 'relative', zIndex: 50 },
      '& .line:has([data-v-twoslash-inline-popup])': {
        position: 'relative',
        paddingBottom: 'var(--vocs-twoslash-popup-height)',
      },
      '& .line:has([data-v-twoslash-completion-popup])': {
        position: 'relative',
        paddingBottom: 'var(--vocs-twoslash-popup-height)',
      },
    },
    '.twoslash-popup-container': {
      zIndex: 50,
      maxWidth: 'calc(0.25rem * 140)',
      borderRadius: theme.vars.borderRadius['sm'],
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      backgroundColor: theme.vars.color.surface,
      WebkitUserSelect: 'none',
      userSelect: 'none',
      '@media (width <= 560px)': { marginInline: 'calc(0.25rem * -1)', maxWidth: '100vw' },
      '& pre': {
        maxHeight: '12.5rem',
        overflowY: 'auto',
        fontSize: '0.75em',
        lineHeight: '1.75em',
        borderStyle: 'solid',
      },
      '& [data-overflows]': {
        maskImage: 'linear-gradient(to bottom, black calc(100% - 2rem), transparent 100%)',
      },
      '& [data-v-overflow-sentinel]': {
        pointerEvents: 'none',
        marginTop: 'calc(0.25rem * -8)',
        height: theme.vars.spacing[8],
      },
      '& pre code': { display: 'grid', whiteSpace: 'pre-wrap' },
      '& .line': { minHeight: '0.5lh' },
      '& .twoslash-popup-docs': { fontSize: '13px' },
      '& [data-v-content] > *': {
        paddingInline: theme.vars.spacing[2],
        paddingBlock: theme.vars.spacing[1],
      },
      '& [data-v-content] > *:not(:last-child)': {
        borderBottomStyle: 'solid',
        borderBottomWidth: '1px',
        borderColor: theme.vars.color.gray['400'],
      },
    },
    '[data-v-twoslash-persisted]': { position: 'relative', display: 'inline-block' },
    '.twoslash-query-persisted.twoslash-popup-container[data-v-twoslash-inline-popup]': {
      position: 'absolute',
      top: 'calc(100% + 0.25rem)',
      left: theme.vars.spacing[0],
      display: 'block',
      width: 'max-content',
      fontSize: theme.vars.fontSize['base'],
    },
    '[data-v-twoslash-inline-arrow]': {
      position: 'absolute',
      top: '-9px',
      left: theme.vars.spacing[3],
      display: 'block',
      lineHeight: 1,
    },
    '[data-v-twoslash-inline-arrow] svg': { display: 'block' },
    '[data-v-twoslash-completion]': { position: 'relative', display: 'inline-block' },
    '[data-v-twoslash-completion-popup]': {
      position: 'absolute',
      top: 'calc(100% + 0.25rem)',
      left: theme.vars.spacing[0],
      display: 'block',
    },
    '[data-v-code-skeleton] [data-v-skeleton-bar]': {
      display: 'inline-block',
      height: '0.72em',
      verticalAlign: 'middle',
      borderRadius: '0.1875rem',
      backgroundColor: theme.vars.color.gray['100'],
      backgroundImage: 'linear-gradient( 90deg, transparent 0%, #8f8f8f 50%, transparent 100% )',
      '@supports (color: color-mix(in lab, red, red))': {
        backgroundImage:
          'linear-gradient( 90deg, transparent 0%, color-mix(in srgb, #8f8f8f 22%, transparent) 50%, transparent 100% )',
      },
      backgroundRepeat: 'no-repeat',
      backgroundSize: '200% 100%',
      animation: 'vocs-skeleton-shimmer 1.25s ease-in-out infinite',
    },
    '@media (prefers-reduced-motion: reduce)': {
      '[data-v-code-skeleton] [data-v-skeleton-bar]': { animation: 'none' },
    },
    '.twoslash-popup-docs': {
      maxHeight: theme.vars.spacing[40],
      overflowY: 'scroll',
      '& > *:not(:last-child)': { marginBottom: theme.vars.spacing[1] },
      '& h1, &  h2, &  h3, &  h4, &  h5, &  h6': {
        marginTop: theme.vars.spacing[2],
        marginBottom: theme.vars.spacing[1],
        fontSize: theme.vars.fontSize['sm'],
        lineHeight: 'calc(1.25 / 0.875)',
        fontWeight: theme.vars.fontWeight['semibold'],
      },
      '& li': { marginBottom: 'calc(0.25rem * 0) !important' },
      '& pre': {
        marginInline: 'calc(0.25rem * -2)',
        backgroundColor: theme.vars.color.gray['100'],
        paddingInline: theme.vars.spacing[2],
        paddingBlock: theme.vars.spacing[1],
      },
    },
    '.twoslash-completion-list': {
      zIndex: 10,
      display: 'flex',
      minWidth: '7.5rem',
      flexDirection: 'column',
      gap: theme.vars.spacing[1],
      borderRadius: theme.vars.borderRadius['sm'],
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      backgroundColor: theme.vars.color.surface,
      padding: theme.vars.spacing[2],
      fontFamily: theme.vars.fontFamily.mono,
      fontSize: theme.vars.fontSize['xs'],
      lineHeight: 'calc(1 / 0.75)',
      WebkitUserSelect: 'none',
      userSelect: 'none',
      '&:hover': { WebkitUserSelect: 'auto', userSelect: 'auto' },
      '& li': {
        display: 'flex',
        alignItems: 'center',
        gap: theme.vars.spacing[1],
        overflow: 'hidden',
        lineHeight: '1em',
        borderStyle: 'solid',
      },
      '& li span.twoslash-completions-matched': { color: theme.vars.color.foreground },
      '& li span.twoslash-completions-unmatched': { color: theme.vars.color.gray['800'] },
      '& .deprecated': {
        color: theme.vars.color.gray['800'],
        textDecorationLine: 'line-through',
        opacity: '50%',
      },
    },
    '.twoslash-highlighted': {
      borderRadius: theme.vars.borderRadius['sm'],
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: theme.vars.color.gray['400'],
      backgroundColor: theme.vars.color.gray['200'],
      '@supports (color: color-mix(in lab, red, red))': {
        backgroundColor: `color-mix(in oklab, ${theme.vars.color.gray['200']} 70%, transparent)`,
      },
      paddingInline: 'calc(0.25rem * 1.5)',
      paddingBlock: 'calc(0.25rem * 0.5)',
    },
    '.twoslash-tag-line': {
      marginBlock: 'calc(0.25rem * 0.5)',
      borderStyle: 'solid',
      paddingBlock: 'calc(0.25rem * 0.5)',
      whiteSpace: 'pre',
    },
    '.twoslash-tag-multiline-line': { marginBlock: theme.vars.spacing[0] },
    '.twoslash-tag-log-line': {
      borderLeftStyle: 'solid',
      borderLeftWidth: '2px',
      borderColor: `${theme.vars.color.blue[900]} !important`,
      backgroundColor: theme.vars.color.blue['100'],
      '@supports (color: color-mix(in lab, red, red))': {
        backgroundColor: theme.vars.color.blue['100'],
      },
      color: theme.vars.color.blue['900'],
    },
    '.twoslash-tag-error-line': {
      borderLeftStyle: 'solid',
      borderLeftWidth: '2px',
      borderColor: `${theme.vars.color.red[900]} !important`,
      backgroundColor: theme.vars.color.red['100'],
      color: theme.vars.color.red['900'],
    },
    '.twoslash-tag-warn-line': {
      borderLeftStyle: 'solid',
      borderLeftWidth: '2px',
      borderColor: `${theme.vars.color.amber[900]} !important`,
      backgroundColor: theme.vars.color.amber['100'],
      '@supports (color: color-mix(in lab, red, red))': {
        backgroundColor: theme.vars.color.amber['100'],
      },
      color: theme.vars.color.amber['900'],
    },
    '.twoslash-tag-annotate-line': {
      borderLeftStyle: 'solid',
      borderLeftWidth: '2px',
      borderColor: `${theme.vars.color.green[900]} !important`,
      backgroundColor: theme.vars.color.green['100'],
      '@supports (color: color-mix(in lab, red, red))': {
        backgroundColor: theme.vars.color.green['100'],
      },
      color: theme.vars.color.green['900'],
    },
    '@layer properties': {
      '@supports ((-webkit-hyphens: none) and (not (margin-trim: inline))) or ((-moz-orient: inline) and (not (color:rgb(from red r g b))))':
        { '*, ::before, ::after, ::backdrop': {} },
    },
  },
})
