import { Config, Vars } from 'zyzz'

const tokens = Vars.define(
  {
    animate: {
      blink: 'var(--vocs-animate-blink)',
      pulse: 'var(--vocs-animate-pulse)',
      spin: 'var(--vocs-animate-spin)',
    },
    backgroundColor: {
      'code-block': 'var(--vocs-background-color-code-block)',
      primary: 'var(--vocs-background-color-primary)',
      surface: 'var(--vocs-background-color-surface)',
      surfaceMuted: 'var(--vocs-background-color-surfaceMuted)',
      surfaceTint: 'var(--vocs-background-color-surfaceTint)',
    },
    blur: {
      md: 'var(--vocs-blur-md)',
      sm: 'var(--vocs-blur-sm)',
    },
    borderColor: {
      primary: 'var(--vocs-border-color-primary)',
      secondary: 'var(--vocs-border-color-secondary)',
    },
    color: {
      accent: 'var(--vocs-color-accent)',
      accent6: 'var(--vocs-color-accent6)',
      accent7: 'var(--vocs-color-accent7)',
      accent8: 'var(--vocs-color-accent8)',
      accent9: 'var(--vocs-color-accent9)',
      accenta3: 'var(--vocs-color-accenta3)',
      accenta4: 'var(--vocs-color-accenta4)',
      accentInvert: 'var(--vocs-color-accentInvert)',
      black: 'var(--vocs-color-black)',
      success: 'var(--vocs-color-success)',
    },
    maxWidth: {
      '2xl': 'var(--vocs-container-2xl)',
      md: 'var(--vocs-container-md)',
      sm: 'var(--vocs-container-sm)',
      xl: 'var(--vocs-container-xl)',
    },
    ease: {
      standard: 'var(--vocs-default-transition-timing-function)',
      'in-out': 'var(--vocs-ease-in-out)',
      out: 'var(--vocs-ease-out)',
    },
    fontFamily: {
      mono: 'var(--vocs-font-mono)',
      sans: 'var(--vocs-font-sans)',
    },
    fontSize: {
      '2xl': 'var(--vocs-text-2xl)',
      '5xl': 'var(--vocs-text-5xl)',
      '6xl': 'var(--vocs-text-6xl)',
      base: 'var(--vocs-text-base)',
      h1: 'var(--vocs-text-h1)',
      lg: 'var(--vocs-text-lg)',
      sm: 'var(--vocs-text-sm)',
      xl: 'var(--vocs-text-xl)',
      xs: 'var(--vocs-text-xs)',
    },
    fontWeight: {
      bold: 'var(--vocs-font-weight-bold)',
      medium: 'var(--vocs-font-weight-medium)',
      semibold: 'var(--vocs-font-weight-semibold)',
    },
    layout: {
      leadingH1: 'var(--vocs-leading-h1)',
      leadingP: 'var(--vocs-leading-p)',
    },
    letterSpacing: {
      normal: 'var(--vocs-tracking-normal)',
      tight: 'var(--vocs-tracking-tight)',
    },
    lineHeight: {
      '2xl': 'var(--vocs-text-2xl--line-height)',
      '5xl': 'var(--vocs-text-5xl--line-height)',
      '6xl': 'var(--vocs-text-6xl--line-height)',
      base: 'var(--vocs-text-base--line-height)',
      lg: 'var(--vocs-text-lg--line-height)',
      sm: 'var(--vocs-text-sm--line-height)',
      xl: 'var(--vocs-text-xl--line-height)',
      xs: 'var(--vocs-text-xs--line-height)',
    },
    radius: {
      '2xl': 'var(--vocs-radius-2xl)',
      lg: 'var(--vocs-radius-lg)',
      md: 'var(--vocs-radius-md)',
      sm: 'var(--vocs-radius-sm)',
      xl: 'var(--vocs-radius-xl)',
    },
    spacing: {
      '0': 'calc(var(--vocs-spacing) * 0)',
      '1': 'calc(var(--vocs-spacing) * 1)',
      '2': 'calc(var(--vocs-spacing) * 2)',
      '3': 'calc(var(--vocs-spacing) * 3)',
      '4': 'calc(var(--vocs-spacing) * 4)',
      '5': 'calc(var(--vocs-spacing) * 5)',
      '6': 'calc(var(--vocs-spacing) * 6)',
      '7': 'calc(var(--vocs-spacing) * 7)',
      '8': 'calc(var(--vocs-spacing) * 8)',
      '10': 'calc(var(--vocs-spacing) * 10)',
      '12': 'calc(var(--vocs-spacing) * 12)',
      '14': 'calc(var(--vocs-spacing) * 14)',
      '16': 'calc(var(--vocs-spacing) * 16)',
      '20': 'calc(var(--vocs-spacing) * 20)',
      '24': 'calc(var(--vocs-spacing) * 24)',
      '28': 'calc(var(--vocs-spacing) * 28)',
      '36': 'calc(var(--vocs-spacing) * 36)',
      '48': 'calc(var(--vocs-spacing) * 48)',
      half: 'calc(var(--vocs-spacing) * 0.5)',
      threeQuarters: 'calc(var(--vocs-spacing) * 0.75)',
      oneAndHalf: 'calc(var(--vocs-spacing) * 1.5)',
      twoAndHalf: 'calc(var(--vocs-spacing) * 2.5)',
      threeAndHalf: 'calc(var(--vocs-spacing) * 3.5)',
      outlineContent: 'calc(var(--vocs-spacing) * 68.5)',
      banner: 'var(--vocs-spacing-banner)',
      content: 'var(--vocs-spacing-content)',
      'content-px': 'var(--vocs-spacing-content-px)',
      'content-py': 'var(--vocs-spacing-content-py)',
      gutter: 'var(--vocs-spacing-gutter)',
      logo: 'var(--vocs-spacing-logo)',
      sidebar: 'var(--vocs-spacing-sidebar)',
      'sidebar-px': 'var(--vocs-spacing-sidebar-px)',
      'sidebar-py': 'var(--vocs-spacing-sidebar-py)',
      topNav: 'var(--vocs-spacing-topNav)',
      unit: 'var(--vocs-spacing)',
    },
    textColor: {
      heading: 'var(--vocs-text-color-heading)',
      link: 'var(--vocs-text-color-link)',
      muted: 'var(--vocs-text-color-muted)',
      primary: 'var(--vocs-text-color-primary)',
      secondary: 'var(--vocs-text-color-secondary)',
    },
    transitionDuration: {
      standard: 'var(--vocs-default-transition-duration)',
    },
  },
  { id: 'vocs' },
)

export const { style, vars } = Config.create({
  id: 'vocs',
  vars: tokens,
  defaultLayer: 'vocs_utilities',
  layers: [
    'vocs_theme',
    'theme',
    'base',
    'vocs_base',
    'vocs_components',
    'components',
    'vocs_utilities',
    'utilities',
  ],
})
