import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import type { PluginOption, ResolvedConfig } from 'vite'
import type * as Config from './config.js'

export function from(options: from.Options = {}): string {
  const { sitemap, basePath = '/' } = options

  const lines = [
    '# AI-friendly robots.txt',
    '# Generated by Vocs - https://vocs.dev',
    '',
    'User-agent: *',
    'Allow: /',
    '',
    '# AI Crawlers',
    'User-agent: Amazonbot',
    'Allow: /',
    '',
    'User-agent: Applebot',
    'Allow: /',
    '',
    'User-agent: Bytespider',
    'Allow: /',
    '',
    'User-agent: CCBot',
    'Allow: /',
    '',
    'User-agent: ChatGPT-User',
    'Allow: /',
    '',
    'User-agent: ClaudeBot',
    'Allow: /',
    '',
    'User-agent: Claude-Web',
    'Allow: /',
    '',
    'User-agent: cohere-ai',
    'Allow: /',
    '',
    'User-agent: Diffbot',
    'Allow: /',
    '',
    'User-agent: GPTBot',
    'Allow: /',
    '',
    'User-agent: Google-Extended',
    'Allow: /',
    '',
    'User-agent: GoogleOther',
    'Allow: /',
    '',
    'User-agent: OAI-SearchBot',
    'Allow: /',
    '',
    'User-agent: PerplexityBot',
    'Allow: /',
    '',
    'User-agent: YouBot',
    'Allow: /',
  ]

  if (sitemap) {
    const sitemapUrl = sitemap.startsWith('http')
      ? sitemap
      : `${sitemap}${basePath === '/' ? '' : basePath}/sitemap.xml`
    lines.push('', `Sitemap: ${sitemapUrl}`)
  }

  return lines.join('\n') + '\n'
}

export declare namespace from {
  type Options = {
    sitemap?: string | undefined
    basePath?: string | undefined
  }
}

export async function hasUserRobots(publicDir: string): Promise<boolean> {
  try {
    await fs.access(path.join(publicDir, 'robots.txt'))
    return true
  } catch {
    return false
  }
}

export function plugin(config: Config.Config): PluginOption {
  let viteConfig: ResolvedConfig

  return {
    name: 'vocs:robots',
    enforce: 'post',
    configResolved(resolvedConfig) {
      viteConfig = resolvedConfig
    },
    configureServer(server) {
      server.middlewares.use(async (req, res, next) => {
        if (req.url !== '/robots.txt') return next()

        const publicDir = path.resolve(viteConfig.root, 'public')
        if (await hasUserRobots(publicDir)) return next()

        const content = from({
          sitemap: config.baseUrl,
          basePath: config.basePath,
        })
        res.setHeader('Content-Type', 'text/plain')
        res.end(content)
      })
    },
    async buildEnd() {
      const publicDir = path.resolve(viteConfig.root, 'public')
      if (await hasUserRobots(publicDir)) return

      const outDir = path.resolve(viteConfig.root, config.outDir, 'public')
      await fs.mkdir(outDir, { recursive: true })

      const content = from({
        sitemap: config.baseUrl,
        basePath: config.basePath,
      })
      await fs.writeFile(path.join(outDir, 'robots.txt'), content, { encoding: 'utf-8' })
    },
  }
}
