name: Main
on:
  push:
    branches: [main, rc]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    if: ${{ github.repository_owner == 'wevm' }}
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  build-twoslash-rust:
    name: Build twoslash-rust
    if: ${{ github.repository_owner == 'wevm' }}
    needs: verify
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
            name: darwin-arm64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: linux-x64-gnu

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: twoslash-rust

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Strip binary
        run: strip target/${{ matrix.target }}/release/twoslash-rust

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.target }}
          path: twoslash-rust/target/${{ matrix.target }}/release/twoslash-rust
          if-no-files-found: error

  changesets:
    name: Changesets
    if: ${{ github.repository_owner == 'wevm' }}
    needs: build-twoslash-rust
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: twoslash-rust/artifacts

      - name: PR or publish
        id: changesets
        uses: changesets/action@v1
        with:
          title: 'chore: version packages'
          commit: 'chore: version packages'
          publish: pnpm run changeset:publish
          version: pnpm run changeset:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          ARTIFACTS_DIR: artifacts
